# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeVideo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SeVideo
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 5.0.6'
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'MJExtension', '~> 3.1.0'
pod 'MJRefresh', '~> 3.2.0'
pod 'FMDB', '~> 2.7.5'
pod 'SJVideoPlayer'
pod 'SJBaseVideoPlayer'
end
